---
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "default" .Release.Namespace }}-fyre-secret
  namespace: {{ default "default" .Release.Namespace }}
data:
  password: {{ b64enc .Values.fyre.credential.username }}
  product_group_id: {{ b64enc .Values.fyre.credential.password }}
  username: {{ b64enc .Values.fyre.credential.product_group_id }}
type: Opaque
